// Mock data for products - similar to chefaa.com pharmacy products

export const categories = [
  { id: "hair", name: "العناية بالشعر", icon: "💇" },
  { id: "skin", name: "العناية بالبشرة", icon: "✨" },
  { id: "body", name: "العناية بالجسم", icon: "🧴" },
  { id: "makeup", name: "ميكب", icon: "💄" },
  { id: "tools", name: "أدوات طبية", icon: "🩺" },
  { id: "baby", name: "أطفال", icon: "👶" },
  { id: "men", name: "رجال", icon: "🧔" },
];

export const products = [
  // Hair Care Products
  {
    id: "2",
    name: "زيوت للشعر متعددة",
    nameEn: "Multi Hair Oil",
    price: 145,
    oldPrice: null,
    category: "hair",
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400",
    description: "زيت شعر طبيعي يغذي ويمنع التساقط",
    inStock: true,
    stock: 30,
    rating: 4.8,
    reviews: 95,
  },
  {
    id: "3",
    name: "ماسك شعر أرغان",
    nameEn: "Argan Hair Mask",
    price: 210,
    oldPrice: 250,
    category: "hair",
    image: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=400",
    description: "ماسك عميق الترطيب للشعر الجاف والمتقصف",
    inStock: true,
    stock: 25,
    rating: 4.3,
    reviews: 67,
  },
  {
    id: "1",
    name: "شامبو كير بروتين ",
    nameEn: "Keratin Protein Shampoo",
    price: 185,
    oldPrice: 220,
    category: "hair",
    image: "https://images.unsplash.com/photo-1585232351009-31338186ce39?w=400",
    description: "شامبو غني بالبروتين الطبيعة لترميم الشعر التالف",
    inStock: true,
    stock: 50,
    rating: 4.5,
    reviews: 128,
  },

  // Skin Care Products
  {
    id: "4",
    name: "كريم ترطيب لليد",
    nameEn: "Hand Moisturizing Cream",
    price: 95,
    oldPrice: 120,
    category: "skin",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    description: "كريم ترطيب عميق لليد والقدمين",
    inStock: true,
    stock: 100,
    rating: 4.6,
    reviews: 210,
  },
  {
    id: "5",
    name: "سيروم للوجه",
    nameEn: "Face Serum Vitamin C",
    price: 350,
    oldPrice: 420,
    category: "skin",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400",
    description: "سيروم فيتامن سي لتفتيح البشرة",
    inStock: true,
    stock: 40,
    rating: 4.9,
    reviews: 156,
  },
  {
    id: "6",
    name: "غسول للوجه",
    nameEn: "Face Wash",
    price: 125,
    oldPrice: null,
    category: "skin",
    image: "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=400",
    description: "غسول وجه لطيف ينظف بعمق",
    inStock: true,
    stock: 60,
    rating: 4.4,
    reviews: 89,
  },

  // Body Care Products
  {
    id: "7",
    name: "لوشن للجسم",
    nameEn: "Body Lotion",
    price: 165,
    oldPrice: 195,
    category: "body",
    image: "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=400",
    description: "لوشن مرطب للجسم بفيتامن إي",
    inStock: true,
    stock: 75,
    rating: 4.7,
    reviews: 134,
  },
  {
    id: "8",
    name: "زيت جوز الهند",
    nameEn: "Coconut Oil",
    price: 180,
    oldPrice: null,
    category: "body",
    image: "https://images.unsplash.com/photo-1589996934895-c5cd2e5d929b?w=400",
    description: "زيت جوز الهند الطبيعي",
    inStock: true,
    stock: 45,
    rating: 4.5,
    reviews: 78,
  },

  // Makeup Products
  {
    id: "9",
    name: "أحمر شفاه",
    nameEn: "Lipstick",
    price: 145,
    oldPrice: 175,
    category: "makeup",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400",
    description: "أحمر شفاه طويل الأمد",
    inStock: true,
    stock: 80,
    rating: 4.2,
    reviews: 112,
  },
  {
    id: "10",
    name: "مكياج كامل",
    nameEn: "Foundation",
    price: 280,
    oldPrice: 320,
    category: "makeup",
    image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=400",
    description: "فاونيشن يغطي العيوب",
    inStock: true,
    stock: 35,
    rating: 4.6,
    reviews: 67,
  },

  // Medical Tools
  {
    id: "11",
    name: "جهاز قياس الضغط",
    nameEn: "Blood Pressure Monitor",
    price: 450,
    oldPrice: 520,
    category: "tools",
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400",
    description: "جهاز قياس ضغط الدم الرقمي",
    inStock: true,
    stock: 15,
    rating: 4.8,
    reviews: 45,
  },
  {
    id: "12",
    name: "جهاز قياس السكر",
    nameEn: "Glucometer",
    price: 380,
    oldPrice: null,
    category: "tools",
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400",
    description: "جهاز قياس السكر في الدم",
    inStock: true,
    stock: 20,
    rating: 4.7,
    reviews: 38,
  },
  {
    id: "13",
    name: "ميزان حرارة",
    nameEn: "Thermometer",
    price: 95,
    oldPrice: 120,
    category: "tools",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    description: "ميزان حرارة رقمي",
    inStock: true,
    stock: 50,
    rating: 4.5,
    reviews: 92,
  },

  // Supplements
  {
    id: "14",
    name: "فيتامن سي 1000",
    nameEn: "Vitamin C 1000mg",
    price: 145,
    oldPrice: null,
    category: "supplements",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400",
    description: "فيتامن سي اقراص للمصلد",
    inStock: true,
    stock: 100,
    rating: 4.6,
    reviews: 187,
  },
  {
    id: "15",
    name: "اوميغا 3",
    nameEn: "Omega 3",
    price: 220,
    oldPrice: 260,
    category: "supplements",
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    description: "اوميقا 3 كبسول لزوم وصحة القلب",
    inStock: true,
    stock: 60,
    rating: 4.8,
    reviews: 145,
  },
  {
    id: "16",
    name: "حديد",
    nameEn: "Iron Supplement",
    price: 85,
    oldPrice: 100,
    category: "supplements",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    description: "حديد اقراص للوقاية من الانيميا",
    inStock: true,
    stock: 80,
    rating: 4.4,
    reviews: 98,
  },

  // Baby Care
  {
    id: "17",
    name: "حليب اطفال",
    nameEn: "Baby Milk",
    price: 320,
    oldPrice: null,
    category: "baby",
    image: "https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=400",
    description: "حليب اطفال من عمر год",
    inStock: true,
    stock: 40,
    rating: 4.9,
    reviews: 234,
  },
  {
    id: "18",
    name: "بامبرز",
    nameEn: "Diapers",
    price: 280,
    oldPrice: 320,
    category: "baby",
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400",
    description: "حفاضات اطفال مقاس 3",
    inStock: true,
    stock: 50,
    rating: 4.7,
    reviews: 167,
  },

  // Men Care
  {
    id: "19",
    name: "جهاز حلاقة",
    nameEn: "Shaver",
    price: 450,
    oldPrice: 520,
    category: "men",
    image: "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=400",
    description: "جهاز حلاقة كهربائي",
    inStock: true,
    stock: 20,
    rating: 4.6,
    reviews: 78,
  },
  {
    id: "20",
    name: "عطر رجالي",
    nameEn: "Men Perfume",
    price: 380,
    oldPrice: 450,
    category: "men",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
    description: "عطر رجالي طويلة الأمد",
    inStock: true,
    stock: 25,
    rating: 4.5,
    reviews: 56,
  },
];

export const getProductById = (id) => {
  return products.find((p) => p.id === id);
};

export const getProductsByCategory = (category) => {
  if (!category || category === "all") {
    return products;
  }
  return products.filter((p) => p.category === category);
};

export const searchProducts = (query) => {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.nameEn.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery),
  );
};
